spring.application.name=DOSW-Library
spring.profiles.active=mongo

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

jwt.secret=dosw-library-jwt-secret-key-2024-secure-signing-key
jwt.expiration=86400000
