name: Library Wars CI/CD Pipeline

# El pipeline se dispara cuando hay un pull_request
on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven Compile
        run: mvn clean compile

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven Verify
        run: mvn verify

  analysis:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Static Analysis
        run: mvn checkstyle:check || echo "Análisis estático completado con advertencias"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Message
        run: echo "En construcción ..."